### PR TITLE
big file structure revamp. settings and globals got organized to help…

### LINKED ISSUE #39: Fix code scanning alert - Wrong type of arguments to formatting function
Tracking issue for:
- [ ] https://github.com/pappde/bmai/security/code-scanning/1

src/bmai.cpp:606
>        void BMC_DieData::Debug(BME_DEBUG _cat)
>        {
>        	BMF_Log(_cat,"(%x)", m_properties & (~BME_PROPERTY_VALID));
>This argument should be of type 'unsigned int' but is of type 'unsigned long'.

after some googling I think the correct formatting syntax for unsigned long is `"(%lu)"`

### LINKED ISSUE #44: Cleanup file structure
One issue with the file structure is inconsistency between classes and headers.  E.g.
1. we have "parser.h" for the BMC_Parser class, but the implementation is in bmail.cpp (should be parser.cpp)
2. "bmai.h" (and bmai.cpp) are mega-files that include multiple classes and definitions
3. arguably, the files should exactly match the class name. E.g. "BMC_Parser.h" instead of "parser.h"
4. header dependencies are not consistent

REQUIREMENTS
Ideally, we would have one header and CPP per class.  

NOTES:
Cleaning up the headers should be straightforward - such as splitting bmai.h into multiple headers (actually added types.h in commit 94ed97d). What is a bit more involved is cleaning up bmai.cpp. For example, there are many dependencies on global/singleton objects declared in bmai.cpp, so we would need to extern them in the header file.

### PR DESCRIPTION
**Pull request by danlangford**
big file structure revamp. settings and globals got organized to help… with dependency tree. fixes #44

im very new to C++ so I dont know if I have the proper use of `extern` and `inline` and `#pragma once` and "forwarding" and "precompiling" but I tried my best, it still compiles and passes its tests, and I am very open to feedback on how to improve it

fixes #39, closes #60

### CODE REVIEW

**Comment by danlangford** [comment]
I apologize for all the random #include commits. I guess my idea and tool chain does need all of those spelled out for some reason. glad that we have these automated builds to catch problems like that.

**Comment by pappde** [comment]
It's a small project, so I wouldn't worry about precompiled headers.  The main thing to remember is that in C/C++ everything needs to be declared before it is used. That generally means either #include the header that defines the class, or you can forward declare (but only in cases where you have pointers only).  It's easier when you don't have circular dependencies.

The other thing that headers in turn will #include dependent headers, and you don't want a header to be included multiple times, so you either use #pragma once or a #ifndef/#define/#endif pattern around the header.

I'll review, but if it's compiling that's a good sign :)

**Review by pappde — CHANGES_REQUESTED** [review]
Overall looks good. The only thing is the main header for the "bmai_lib" module:
1) currently named "bmai.h", it would make more sense to call it "bmai_lib.h"
2) remove the main() declaration from that header file.

File: src/BMC_Game.h [hunk 1]
```diff
@@ -120,4 +124,7 @@ class BMC_Game		// 420b
 	bool		m_simulation;
 
 	bool		m_surrender_allowed;
-};
\ No newline at end of file
+};
+
+// global
+inline BMC_Game g_game(false);
```
Comment (pappde) [inline src/BMC_Game.h:130]: Can't "inline" a global. You'll end up with one g_game in each CPP file that includes it.  See comments in bmai_ai.h

File: src/bmai_ai.h [hunk 2]
```diff
@@ -4,182 +4,27 @@
...
-class BMC_AI_Mode2 : public BMC_AI
-{
-};
-
-
-#endif // #ifndef __BMAI_AI_H__
\ No newline at end of file
+// found this one bouncing around somewhere also
+// TODO audit g_qai and g_qai2 usage. are both needed?
+inline BMC_QAI	g_qai;
```
Comment (pappde) [inline src/bmai_ai.h:30]: Need to change how globals are handled. For each global:
1) first identify if it even needs to be a global.  Can it just be locally owned?
E.g. "g_ai_type" is only used in BMC_Parser.  So you can just define it in BMC_Parser.cpp then you don't need to mention it in the header.

2) if it needs to be global, then:
2.1) instance it in a CPP file.  
E.g. BMC_Game.cpp defines "BMC_Game g_game"
2.2) "extern" it in the header file (like an export) so that other modules can link to it.
E.g. BMC_Game.h defines "extern BMC_Game g_game"

However, g_game is only used by BMC_Parser, so it can just be instanced there.

**Review by pappde — CHANGES_REQUESTED** [review]
GLOBALS
Recommendation is to get rid of the ones we can, and at least remove them from the header files. Definitely don't "inline" them.  The "inline" keyword will instance that in every CPP that #includes it.

Some specific ones:
1) BMC_Game g_game is only used by BMC_Parser, so just define the global in BMC_Parser.cpp, and remove it from the header.
2) g_ai_mode3: only used in BMC_Parser, so the same. In fact, this one already is instanced in BMC_Parser.cpp. You can again just remove it from the header.
3) g_ait_type should be defined in BMC_Parser.cpp and removed from the header.

Actually, I recommend deleting bmai_ai.h and then just seeing what you need to fix.

File: src/bmai_ai.h (hunk 2 above)
Comment (pappde) [reply src/bmai_ai.h:30]: Per other comment, I recommend:
1) move g_ai_type to BMC_Parser.cpp
2) delete bmai_ai.h

File: src/BMC_Logger.h [hunk 3]
```diff
@@ -29,4 +33,19 @@ class BMC_Logger
...
 private:
 	bool			m_logging[BME_DEBUG_MAX];
-};
\ No newline at end of file
+};
+
+
+// To address a cyclical dependency the global logger can live here for now
+// TODO address & understand g_logger.Log() vs BMF_Log()
+inline BMC_Logger	g_logger;
```
Comment (pappde) [inline src/BMC_Logger.h:41]: 1) instance in the CPP. I.e. "BMC_Logger g_logger;"
2) change to "extern" in the Header

File: src/BMC_RNG.h [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+  F32	GetFRand()		{ return (float)GetRand() / (float)0x80000000; }
+  UINT	GetRand();
+  void	SRand(UINT _seed);
+
+private:
+  UINT	m_seed;
+};
+
+// global
+inline BMC_RNG		g_rng;
```
Comment (pappde) [inline src/BMC_RNG.h:31]: 1) instance in the CPP
2) change header to "extern"

File: src/BMC_Stats.h [hunk 5]
```diff
@@ -34,4 +37,7 @@ class BMC_Stats
 	int				m_total_moves[BMD_MAX_PLY];
 	int				m_total_samples[BMD_MAX_PLY];
 
-};
\ No newline at end of file
+};
+
+// global
+inline BMC_Stats  g_stats;
```
Comment (pappde) [inline src/BMC_Stats.h:43]: 1) instance in the CPP
2) change header to "extern"

**Review by pappde — CHANGES_REQUESTED** [review]
A few more inlined globals noted.

**Comment by pappde** [comment]
GLOBALS
I added several comments about how to handle globals. Unfortunately, a lot of redundant/overlapping comments since a lot of files in the commit, but I'll summarize again here.  

If you need a global (e.g. BMC_RNG g_rng is a good one)
1) pick a file to instance the global. Either BMC_RNG.cpp, or in a main CPP for the library
2) instance the global in that file. E.g. in the CPP:
BMC_RNG g_rng;
3) if other modules need to reference it, then add an "extern" (not "inline") declaration in the matching header:
extern BMC_RNG g_rng;

That tells the linker that when a module references g_rng it looks for the symbol in the other modules.

**Comment by danlangford** [comment]
thank you so much much. I was naively thinking `inline` was something of a shortcut to having the instance in the .cpp and then using `extern`. ill go address ALL the `inline`s 

I appreciate the feedback here

**Comment by danlangford** [comment]
@pappde ok I think im ready for you to take another pass across this is thats cool with you

File: src/BMC_Parser.cpp [hunk 6]
```diff
@@ -22,12 +22,36 @@
...
+	"preround",
+	"reserve",
+	"initiative",
+	"chance",
+	"focus",
+	"fight",
+	"gameover"
+};
+
+BMC_Game m_game(false);
```
Comment (pappde) [inline src/BMC_Parser.cpp:44]: Technically, these are all still "globals" (all the m_* objects), so the "m_" prefix isn't appropriate as it is for member variables of a class.  They aren't visible to other modules, since you don't have an "extern" statement anywhere.   So how they should be handled, either.

A) rename them to "g_*" (e.g. g_game) since that is the prefix for globals
B) move them to be member properties of the BMC_Parser. You would then use the BMC_Parser() ctor to either initialize them directly, or allocate them if using pointers. E.g. as a member object you pass parameters via initializer list
```
BMC_Parser.h
...
    BMC_Game m_game

...
BMC_Parser.cpp
  BMC_Player::BMC_Parser() : m_game(false)
```

As a member pointer, you instead do an explicit new and delete, but the codebase does generally try to avoid this pattern.

UPDATE: 
After observing the "AI" objects are easiest to leave as global (e.g. g_qai), I still think you can go either way with BMC_Game - either as a global or as a member object. The latter is probably cleaner though.

File: src/BMC_Parser.cpp [hunk 7]
```diff
@@ -22,12 +22,36 @@
...
-#include "bmai_ai.h"
+#include "BMC_BMAI3.h"
 #include "BMC_Logger.h"
+#include "BMC_QAI.h"
 #include "BMC_RNG.h"
 #include "BMC_Stats.h"
 
 
+// PHASE names
+const char *m_phase_name[BME_PHASE_MAX] =
```
Comment (pappde) [inline src/BMC_Parser.cpp:33]: This is configuration data that is declared globally. The "m_" prefix is for member variables. Configuration should stay global (don't move to a class property), but recommend adopting a "c_" prefix.  E.g.

```
const char *c_phase_name...
```

File: src/BMC_Logger.cpp [hunk 8]
```diff
@@ -20,6 +20,22 @@
 #include <string>
 
 
+// BME_DEBUG setting names
+const char *g_debug_name[BME_DEBUG_MAX] =
```
Comment (pappde) [inline src/BMC_Logger.cpp:24]: While "g_" is appropriate in this case, I suggested elsewhere the idea of adopting a "c_" prefix for global variables that are constant/configuration.  E.g. *c_debug_name*

File: src/BMC_Die.cpp [hunk 9]
```diff
@@ -17,6 +17,15 @@
 #include "BMC_Player.h"
 #include "BMC_RNG.h"
 
+//X?: Roll a d6. 1: d4; 2: d6; 3: d8; 4: d10; 5: d12; 6: d20.
+//V?: Roll a d4. 1: d6; 2: d8; 3: d10; 4: d12.
+INT m_mood_sides_X[BMD_MOOD_SIDES_RANGE_X] = { 4, 6, 8,  10, 12, 20 };
```
Comment (pappde) [inline src/BMC_Die.cpp:22]: Global configuration. Noted elsewhere these should be "c_mood_sides_X" (if we adopt the convention, or "g_mood..." if not)

File: src/BMC_Parser.cpp [hunk 10]
```diff
@@ -22,12 +22,36 @@
...
+BMC_Game m_game(false);
+
+// other AI instances that were once global
+BMC_QAI		m_qai;
+BMC_BMAI3	m_ai(&m_qai);
+BMC_QAI		m_qai2;
+BMC_BMAI	m_bmai(&m_qai);
+BMC_BMAI3	m_bmai3(&m_qai);
+
+BMC_AI * m_ai_type[BMD_AI_TYPES] = { &m_bmai, &m_qai2, &m_bmai3 };
```
Comment (pappde) [inline src/BMC_Parser.cpp:53]: Prefix "m_" is for member variables. These are global, so the "g_" prefix.  E.g.

```
BMC_QAI g_qai;
```

Recommend leaving the other ones as global as well.

```
BMC_BMAI3 g_ai(&g_qai);
```

Comment (pappde) [inline src/BMC_Parser.cpp:53]: Per other comments, recommend adopting other prefixes and using "s_ai_type".  Will comment generally about prefixes separately.

File: src/BMC_BMAI.cpp [hunk 11]
```diff
@@ -29,7 +28,7 @@ INT BMC_BMAI::sm_debug_level = 2;		// default so only up to level 2 is output
 // BMAI methods
 ///////////////////////////////////////////////////////////////////////////////////////////
 
-BMC_BMAI::BMC_BMAI() : m_qai(&g_qai)
+BMC_BMAI::BMC_BMAI(BMC_AI * _ai) : m_qai(_ai)
```
Comment (pappde) [inline src/BMC_BMAI.cpp:31]: I noticed "m_qai" is actually owned by the base class BMC_AI, but is only used by BMC_BMAI.  That property should be moved to the BMC_BMAI class declaration.

**Review by pappde — CHANGES_REQUESTED** [review]
The main issue is with naming (the prefix) of the globals. Propose the following:

- g_ for global objects that have state, function, etc. E.g. g_qai
- c_ for constant configuration. E.g. c_phase_name
- s_ for tweakable configuration. E.g. s_ply_decay or s_ai_type.

The "m_" prefix should only be used for member variables (meaning defined in the class declaration/ header file).

A couple of other comments were:

2. perhaps m_game should indeed be a member variable of class BMC_Parser
3. BMC_AI::m_qai should probably be moved up a class to BMC_BMAI::m_qai

**Comment by pappde** [comment]
Updated review, primarily just naming.  

Moving objects from global to member variables passed via constructors is a good move. Globals generally should be avoided. One thing to remember is that a global is anything defined outside of the class definition. Some things that I believe are ok to stay global:

- all of the configuration/definitions, but I recommended c_ prefixes for these
- singleton type service objects like g_rng and g_logger
- maybe the different AI objects.  You could move them to member variables, but without getting into memory allocation, passing initializer parameters has some limitations.

File: src/BMC_Parser.cpp (hunk 10 above)
Comment (pappde) [reply src/BMC_Parser.cpp:53]: If you wanted to move these to member variables as well, perhaps get away from the constructor initializer list and instead change to explicit initialization. E.g.

```
class BMC_Parser
   ...
   BMC_QAI m_qai
   BMC_BMAI3 m_ai

constructor BMC_Parser::BMC_Parser() : m_game(false)
{
   ...
  m_ai.SetQAI(&m_qai)
}
```

**Comment by danlangford** [comment]
I know these reviews are big and I really appreciate you taking the time. And they are likely quite annoying. Coming from mainly Java I forget that scoping is different and that just because the .cpp compile unit is primarily focused on class method implementation it doesn’t mean everything in that file is scoped to the class. 🤦

**Comment by danlangford** [comment]
@pappde I did a pass on some naming.

**Review by pappde — APPROVED** [review]
